apiversion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchlabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: rohit220199/flask-app:latest
      
